name: gql_generator
description: Graph QL code generator
version: 0.0.2
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  build: ^2.3.1
  source_gen: ^1.2.5
  gql_annotation:
    path: ../gql_annotation

dev_dependencies:
  #build_test: ^0.10.11
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter

flutter:
