name: gql_generator
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: '>=1.2.2 <2.0.0'
  source_gen: ^0.9.4+6
  gql_annotation:
    path: ../gql_annotation

dev_dependencies:
  #build_test: ^0.10.11
  build_runner: '>=1.7.2 <2.0.0'
  flutter_test:
    sdk: flutter

flutter:
